# Generated by Django 4.0.3 on 2022-03-05 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_address_zip'),
    ]

    operations = [
        migrations.RunSQL("""
            INSERT INTO store_collection(title)
            VALUES ('collection1')
        ""","""
            DELETE FROM store_collection
            WHERE title = 'collection1'
        """)
    ]
