# Generated by Django 4.0.3 on 2022-03-05 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20220305_1152'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='membreship',
            new_name='membership',
        ),
    ]
